### ISSUE TITLE
Subtract with overflow in inflate crate

### ISSUE THREAD

**Issue by mateon1** [PistonDevelopers/image-png#65]
This png file reproduces the issue: http://en.blitzortung.org/Flags/eu.png
To reproduce, run `examples/show.rs` in debug mode, or enable overflow-checks in Cargo.toml

I tried to report this directly to the inflate crate, but I couldn't manually craft a rust file that crashed.

Stack trace:
```gdb
thread 'main' panicked at 'attempt to subtract with overflow', /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.2.0/src/lib.rs:583:27
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: inflate::InflateStream::run_len_dist
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.2.0/src/lib.rs:583
  11: inflate::InflateStream::next_state
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.2.0/src/lib.rs:863
  12: inflate::InflateStream::update
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/inflate-0.2.0/src/lib.rs:1053
  13: png::decoder::stream::StreamingDecoder::next_state
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/stream.rs:362
  14: png::decoder::stream::StreamingDecoder::update
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/stream.rs:169
  15: <png::decoder::ReadDecoder<R>>::decode_next
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/mod.rs:109
  16: <png::decoder::Reader<R>>::next_raw_interlaced_row
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/mod.rs:428
  17: <png::decoder::Reader<R>>::next_interlaced_row
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/mod.rs:254
  18: <png::decoder::Reader<R>>::next_row
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/mod.rs:238
  19: <png::decoder::Reader<R>>::next_frame
             at /home/mateon/.cargo/registry/src/github.com-1ecc6299db9ec823/png-0.9.0/src/decoder/mod.rs:229
  20: show::load_image
             at /shared/dev/rust/image-png/examples/show.rs:23
  21: show::main_loop
             at /shared/dev/rust/image-png/examples/show.rs:64
  22: show::main
             at /shared/dev/rust/image-png/examples/show.rs:194
  23: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  24: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  25: main
  26: __libc_start_main
  27: _start
```

**Comment by potocpav** [comment]
Fixed upstream

**Comment by Shnatsel** [comment]
This issue is resolved and should be closed.

**Comment by bvssvni** [comment]
Thanks! Closing.
